name: Python Unit Test

on:
  push:
    paths:
      - 'yildiz.py'
  pull_request:
    paths:
      - 'yildiz.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unittest
    
    - name: Run tests
      run: |
        python -m unittest test_yildiz.py
    
    - name: Create result file
      run: |
        if [ $? -eq 0 ]; then
          echo "Tüm testler geçti! 100 puan kazandınız." > not.txt
        else
          echo "Testlerden en az biri başarısız oldu. Puanınız 0." > not.txt
        fi
    
    - name: Commit result file
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@users.noreply.github.com"
        git add not.txt
        git commit -m "Test sonuçları güncellendi"
      if: success() || failure()
    
    - name: Upload result
      uses: actions/upload-artifact@v3
      with:
        name: test-result
        path: not.txt
