name: Python Unit Test

on:
  push:
    paths:
      - 'yildiz.py'
  pull_request:
    paths:
      - 'yildiz.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    
    - name: Run tests
      id: test-results
      run: |
        if python -m unittest test_yildiz.py; then
          echo "Tüm testler geçti! 100 puan kazandınız." > not.txt
        else
          echo "Testlerden en az biri başarısız oldu. Puanınız 0." > not.txt
        fi
    
    - name: Commit result file to branch
      env:
        ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@users.noreply.github.com"
        
        # Eğer bu bir PR'den geliyorsa, HEAD referansını al
        BRANCH_NAME="${{ github.head_ref }}"
        
        # Eğer push olayıyla çalışıyorsa, aktif branch'i al
        if [ -z "$BRANCH_NAME" ]; then
          BRANCH_NAME="${{ github.ref_name }}"
        fi

        git checkout $BRANCH_NAME
        git add not.txt
        git commit -m "Test sonuçları eklendi"
        git push origin HEAD:$BRANCH_NAME
